app = "chasecart-poc"
primary_region = "cdg"

[build]

[env]
  NODE_ENV = "production"
  FIREBASE_PROJECT_ID = ""

[[services]]
name = "backend"
internal_port = 5000
protocol = "tcp"
auto_start_machines = true
auto_stop_machines = true
min_machines_running = 0

[services.http_checks]
path = "/health"
interval = "30s"
timeout = "5s"

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443 
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1